import { FirebaseAuthProvider, useFirebaseAuth } from "@/contexts/FirebaseAuthContext";
import { firestore } from "@/lib/firebase";
import { addDoc, collection, doc, getDocs, limit, orderBy, query, serverTimestamp, setDoc, where } from "firebase/firestore";
import { ArrowRight, Check, ChevronRight, CircleUserRound, Compass, FileText, FolderPlus, HeartHandshake, LayoutDashboard, LogOut, Menu, MoveUpRight, Plus, Settings, Sparkles, X } from "lucide-react";
import React, { useEffect, useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import SynapseWorkspace from "./SynapseWorkspace";
import { protectedRouteDestination } from "@/lib/routeGuard";

const projectStages = ["Frame", "Explore", "Choose", "Plan"];
type Project = { id: string; title: string; stage?: string; updatedAt?: { toDate?: () => Date } };

function Brand() { return <Link href="/" className="morrow-brand"><span className="morrow-mark">M</span><span>Morrow</span></Link>; }
function PublicNav() { return <header className="public-nav"><Brand /><nav><a href="#how">How it works</a><Link href="/pricing">Pricing</Link><Link href="/faq">FAQ</Link><Link href="/login" className="quiet-link">Sign in</Link><Link href="/signup" className="nav-cta">Start planning <ArrowRight size={15}/></Link></nav></header>; }

function Landing() { return <main className="morrow-site"><PublicNav /><section className="morrow-hero"><div className="hero-copy"><p className="overline">A clearer way to start</p><h1>Turn a good instinct<br/>into a great <em>project.</em></h1><p className="lede">Morrow gives ambitious teams a calm, practical space to shape ideas, choose the strongest direction, and make a plan they can actually deliver.</p><div className="hero-actions"><Link href="/signup" className="primary-link">Start a new project <ArrowRight size={17}/></Link><a className="secondary-link" href="#how">See how it works</a></div><p className="micro-proof"><Check size={15}/> Thoughtful planning for fast-moving teams</p></div><div className="hero-paper" aria-label="Preview of a Morrow project brief"><div className="paper-label">New project · Weekend build</div><h2>Make every decision<br/>feel intentional.</h2><div className="paper-rule"/><div className="paper-row"><span>01</span><p>What are we here to solve?</p></div><div className="paper-row"><span>02</span><p>What can we meaningfully ship?</p></div><div className="paper-row active"><span>03</span><p>Which idea earns the weekend?</p><ChevronRight size={16}/></div><div className="paper-scribble">clear path, better work</div></div></section>
  <section className="trust-strip"><span>Less noise.</span><span>Better decisions.</span><span>More finished work.</span></section>
  <section className="story-section" id="how"><div className="section-intro"><p className="overline">From possibility to plan</p><h2>Four small moves<br/>that change the whole sprint.</h2></div><div className="story-list">{[["01","Frame the challenge","Start with your real constraints, strengths, and the problem worth caring about."],["02","Explore directions","See distinct, considered possibilities instead of a sprawling list of maybes."],["03","Choose with confidence","Compare the trade-offs side by side and commit to the direction with the best chance of landing."],["04","Build with purpose","Leave with a sensible feature list, a team plan, and a story worth telling."]].map(([n,title,copy]) => <article key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
  <section className="outcome-section"><div><p className="overline">Built for momentum</p><h2>Planning should feel<br/>like making progress.</h2><p>Morrow keeps the creative work human: it helps your team focus, settle the hard questions, and move forward together.</p><Link href="/signup" className="text-link">Make your first project <ArrowRight size={16}/></Link></div><div className="outcome-grid"><div><Sparkles/><strong>Focused</strong><span>Scope the work that fits the moment.</span></div><div><HeartHandshake/><strong>Shared</strong><span>Give every teammate the same clear picture.</span></div><div><Compass/><strong>Practical</strong><span>Turn insight into work your team can start.</span></div><div><FileText/><strong>Portable</strong><span>Take a clean plan into your tools and pitch.</span></div></div></section>
  <section className="closing-cta"><p className="overline">Ready when you are</p><h2>Your next project deserves<br/>a strong beginning.</h2><Link href="/signup" className="primary-link">Start planning for free <ArrowRight size={17}/></Link></section><footer className="morrow-footer"><Brand/><span>© {new Date().getFullYear()} Morrow</span><Link href="/pricing">Pricing</Link><Link href="/login">Sign in</Link></footer></main>; }

 function AuthPage({ mode }: { mode: "login" | "signup" | "reset" }) { const { login, signup, loginWithGoogle, resetPassword } = useFirebaseAuth(); const [, setLocation] = useLocation(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [pending,setPending]=useState(false); const title = mode === "signup" ? "Make a better start." : mode === "reset" ? "Reset your password." : "Welcome back."; const destination = mode === "signup" ? "/app/onboarding" : "/app"; const submit = async (event: React.FormEvent) => { event.preventDefault(); setPending(true); try { if(mode === "login") await login(email,password); else if(mode === "signup") await signup(email,password); else { await resetPassword(email); toast.success("Password reset email sent."); setPending(false); return; } setLocation(destination); } catch (error) { toast.error(error instanceof Error ? error.message : "Something went wrong."); } setPending(false); }; return <main className="auth-page"><Link href="/" className="auth-back"><ArrowRight size={16}/> Back to Morrow</Link><section className="auth-card"><Brand/><p className="overline">{mode === "signup" ? "Begin your workspace" : "Your Morrow account"}</p><h1>{title}</h1><p>{mode === "reset" ? "We’ll send a reset link to your inbox." : mode === "signup" ? "A calm place for your team’s best work." : "Pick up where your last good idea left off."}</p>{mode !== "reset" && <Button className="google-button" variant="outline" onClick={async()=>{try{await loginWithGoogle();setLocation(destination);}catch(error){toast.error(error instanceof Error?error.message:"Google sign-in failed.");}}}>Continue with Google</Button>} {mode !== "reset" && <div className="auth-divider"><span/>or continue with email<span/></div>}<form onSubmit={submit}><label>Email<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label>{mode !== "reset" && <label>Password<Input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required /></label>}<Button type="submit" disabled={pending}>{pending ? "Please wait…" : mode === "signup" ? "Create account" : mode === "reset" ? "Send reset link" : "Sign in"}</Button></form><p className="auth-switch">{mode === "login" ? <>New here? <Link href="/signup">Create an account</Link> · <Link href="/forgot-password">Forgot password?</Link></> : mode === "signup" ? <>Already have an account? <Link href="/login">Sign in</Link></> : <Link href="/login">Back to sign in</Link>}</p></section></main>; }

function AppShell({ children }: { children: React.ReactNode }) { const { user, logout }=useFirebaseAuth(); const [location,setLocation]=useLocation(); const [open,setOpen]=useState(false); const links=[["/app",LayoutDashboard,"Overview"],["/app/projects/new",FolderPlus,"New project"],["/app/settings",Settings,"Settings"]] as const; return <div className="app-shell"><aside className={open?"sidebar open":"sidebar"}><Brand/><button className="close-nav" onClick={()=>setOpen(false)}><X/></button><nav>{links.map(([href,Icon,label])=><button key={href} className={location===href?"is-active":""} onClick={()=>{setLocation(href);setOpen(false)}}><Icon size={17}/>{label}</button>)}</nav><div className="sidebar-bottom"><span className="avatar">{(user?.displayName||user?.email||"M").slice(0,1).toUpperCase()}</span><div><strong>{user?.displayName||"Your workspace"}</strong><small>{user?.email}</small></div><button aria-label="Sign out" onClick={async()=>{await logout();setLocation("/");}}><LogOut size={16}/></button></div></aside><div className="app-main"><header className="app-top"><button className="mobile-menu" onClick={()=>setOpen(true)}><Menu/></button><p>{location.includes("settings")?"Settings":location.includes("new")?"New project":"Your workspace"}</p><Button onClick={()=>setLocation("/app/projects/new")}><Plus/>New project</Button></header>{children}</div></div>; }
function Dashboard() { const { user }=useFirebaseAuth(); const [,setLocation]=useLocation(); const [projects,setProjects]=useState<Project[]>([]); const [loading,setLoading]=useState(true); useEffect(()=>{let active=true;(async()=>{if(!firestore||!user){setLoading(false);return;} const snapshot=await getDocs(query(collection(firestore,"projects"),where("ownerId","==",user.uid),orderBy("updatedAt","desc"),limit(8)));if(active){setProjects(snapshot.docs.map(d=>({id:d.id,...d.data()} as Project)));setLoading(false);}})().catch(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user]); return <AppShell><main className="dashboard"><section className="dashboard-welcome"><div><p className="overline">Good to see you</p><h1>Where would you like<br/>to make progress?</h1><p>Start a fresh project or return to the work already taking shape.</p></div><button className="new-project-card" onClick={()=>setLocation("/app/projects/new")}><span><Plus/></span><strong>Start something new</strong><small>Frame a new challenge</small></button></section><section className="usage-strip"><div><span>Current plan</span><strong>Free workspace</strong></div><div><span>Projects</span><strong>{loading ? "—" : projects.length}</strong></div><div><span>What’s included</span><strong>Plans & exports</strong></div></section><section className="dashboard-section"><div className="section-title"><h2>Recent projects</h2><button onClick={()=>setLocation("/app/projects/new")}>View all <ArrowRight size={15}/></button></div>{loading?<div className="project-grid skeletons"><span/><span/><span/></div>:projects.length?<div className="project-grid">{projects.map(project=><button className="project-card" key={project.id} onClick={()=>setLocation(`/app/projects/${project.id}`)}><span className="project-dot"/><p>{project.stage||"Framing"}</p><h3>{project.title}</h3><small>Continue planning <ArrowRight size={14}/></small></button>)}</div>:<div className="first-empty"><span className="empty-mark"><Compass/></span><div><h3>Your first project starts here.</h3><p>Bring a vague idea, a real problem, or a blank page. Morrow will help you find the shape of the work.</p><Button onClick={()=>setLocation("/app/projects/new")}>Create your first project <ArrowRight/></Button></div></div>}</section></main></AppShell>; }
function NewProject() {
  const { user } = useFirebaseAuth(); const [, setLocation] = useLocation();
  const [title, setTitle] = useState(""); const [creating, setCreating] = useState(false);
  const createProject = async (event: React.FormEvent) => {
    event.preventDefault(); if (!title.trim() || !firestore || !user) return;
    setCreating(true);
    try {
      const ref = await addDoc(collection(firestore, "projects"), { ownerId: user.uid, title: title.trim(), stage: "Framing", createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
      setLocation(`/app/projects/${ref.id}`);
    } catch { toast.error("We couldn't create that project. Please try again."); }
    setCreating(false);
  };
  return <AppShell><main className="new-project"><Link href="/app" className="back-app">← Back to workspace</Link><p className="overline">New project</p><h1>What are you<br/>setting out to make?</h1><p>Give this piece of work a name. You can add the details once you’re inside.</p><form onSubmit={createProject}><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. The case for better campus nights" autoFocus/><Button type="submit" disabled={creating || !title.trim()}>{creating ? "Creating…" : "Start framing"}<ArrowRight/></Button></form></main></AppShell>;
}
function ProjectWorkspace(){const[location]=useLocation();const projectId=location.split("/")[3]||"";return <AppShell><div className="morrow-integrated-studio"><SynapseWorkspace projectId={projectId} embedded/></div></AppShell>}
function SettingsPage(){const {user}=useFirebaseAuth();return <AppShell><main className="settings-page"><p className="overline">Settings</p><h1>Your account</h1><section><CircleUserRound/><div><strong>{user?.displayName||"Morrow member"}</strong><span>{user?.email}</span></div></section><p className="settings-note">Your planning workspace is private to your account. Account management and sign-in settings are handled through Firebase Authentication.</p></main></AppShell>}
function Protected({children}:{children:React.ReactNode}){const{user,loading}=useFirebaseAuth();const[,setLocation]=useLocation();const destination=protectedRouteDestination(user?.uid,loading);useEffect(()=>{if(destination==="login")setLocation("/login")},[destination,setLocation]);return destination==="loading"?<div className="auth-loading">Loading your workspace…</div>:destination==="allow"?<>{children}</>:null}
function Routes(){return <Switch><Route path="/" component={Landing}/><Route path="/pricing"><Pricing/></Route><Route path="/faq"><Faq/></Route><Route path="/login"><AuthPage mode="login"/></Route><Route path="/signup"><AuthPage mode="signup"/></Route><Route path="/forgot-password"><AuthPage mode="reset"/></Route><Route path="/app/onboarding"><Protected><Onboarding/></Protected></Route><Route path="/app"><Protected><Dashboard/></Protected></Route><Route path="/app/projects/new"><Protected><NewProject/></Protected></Route><Route path="/app/projects/:id"><Protected><ProjectWorkspace/></Protected></Route><Route path="/app/settings"><Protected><SettingsPage/></Protected></Route><Route><Landing/></Route></Switch>}
function Pricing(){return <main className="pricing-page"><PublicNav/><section><p className="overline">Simple by design</p><h1>Start free. Stay focused.</h1><p>Everything your team needs to frame a strong project and create a real plan.</p><div className="price-card"><span>Free workspace</span><strong>$0</strong><small>For individual builders and early teams</small><ul><li>Private project workspace</li><li>Idea directions and comparison</li><li>Editable project blueprint</li><li>Markdown export</li></ul><Link href="/signup" className="primary-link">Start planning <ArrowRight size={16}/></Link></div></section></main>}
function Faq(){return <main className="pricing-page"><PublicNav/><section><p className="overline">Questions, answered</p><h1>Plan less around the work. Do more of it.</h1><div className="price-card faq-list"><h3>Who is Morrow for?</h3><p>Small teams who want to turn a promising challenge into a focused, buildable project.</p><h3>Do I need a finished idea?</h3><p>No. A half-formed instinct, a problem, or a moment of friction is a useful place to begin.</p><h3>Can I share the plan with my team?</h3><p>Yes. Morrow gives you a portable blueprint you can take into your existing workflow.</p></div></section></main>}
function Onboarding(){const[,setLocation]=useLocation();return <AppShell><main className="new-project"><p className="overline">Welcome to Morrow</p><h1>Start small. Make it count.</h1><p>Every strong project starts with a clear first question. Create a workspace, frame the challenge, and let the rest take shape from there.</p><Button onClick={()=>setLocation("/app/projects/new")}>Create your first project <ArrowRight/></Button></main></AppShell>}
export default function MorrowApp(){return <FirebaseAuthProvider><Routes/></FirebaseAuthProvider>}
